### ISSUE TITLE
nacteni .psd a .tif

### ISSUE THREAD

**Issue by pelcv** [LenticularSoftworks/lenticulis-gui#10]
při přetažení .psd do časové osy program zamrzne neodpovídá
při přetažení .tif skočí hláška Chyba při načítání obrázku (byla vyvolána výjmka)

**Comment by MartinUbl** [comment]
Problém izolován - poskytnuté PSD mělo jen pozadí, tedy žádné vrstvy, a načítací rutina v podpůrné knihovně předpokládala přítomnost vrstev, které adresuje pomocí číselných indexů, a čeká na chybu. Ta nepřišla a aplikace se zacyklila

U obrázku typu TIF je problém v knihovně ImageMagick, kde předpokládá sekvenci, kterou sice je schopno oželet, ale zároveň s tím vyhazuje výjimku (svou podstatou spíše varovnou), a s tím frontend nepočítá.

Obě chyby předány Davidovi.
